%{
  #include <iostream> // std::cout, std::endl
  #include <sstream> // std::stringstream, std::istringstream

  #include "nodename_machine.hpp"

  using namespace std;
  using namespace Nodename;

  extern FILE *yyin;   // Declaration of the yyin variable generated by lex that points to the input file
  extern char *yytext; // Declaration of the yytext variable generated by lex
  extern int yylineno; // Declaration of yylineno variable generated by lex
  extern int yycolumn; // Declaration of yycolumn variable defined in yacc file

  extern int yylex(void); // Declaration of the yylex function generated by lex
  int yyerror(const char *s); // Declaration of the yyerror function defined below

  std::string nodenameResultToString(Nodename::NodenameResult); // Auxiliary function defined below
%}

%code requires {
  #include <string>
  #include "nodename_result.hpp"
}

/* Definition of union used to define terminal and non-terminal types */
/* TODO: Verify if num is really necessary */
%union {
  std::string *lexem;
  Nodename::NodenameResult *nodenameResult;
};

%token <lexem> op end_marker lpar nodename rpar terminal_and terminal_not terminal_or turnsto

%type <lexem> start
%type <lexem> search_expression
%type <lexem> opt_restrictions
%type <lexem> restrictions
%type <lexem> restrictions_and
%type <lexem> restrictions_not
%type <lexem> restriction
%type <lexem> search_second
%type <lexem> search_primary
%type <nodenameResult> node_specifier

%%

start:
  search_expression // turnsto replacement_expression
    {
      stringstream ss;

      ss << "{";
      ss << "search_expression:" << *$1;
      ss << "}";

      string s = ss.str();
      cout << s << endl;
      $$ = new string(s);
    }
  ;

search_expression:
  search_primary opt_restrictions
    {
      stringstream ss;

      ss << "{";
      ss << "search_primary:" << *$1 << ",";
      ss << "opt_restrictions:" << *$2;
      ss << "}";

      $$ = new string(ss.str());
    }
  ;

opt_restrictions:
  restrictions
    {
      stringstream ss;

      ss << "{";
      ss << "restrictions:" << *$1;
      ss << "}";

      $$ = new string(ss.str());
    }
  |
    {
      $$ = new string();
    }
  ;

restrictions:
  restrictions terminal_or restrictions_and
    {
      stringstream ss;

      ss << "{";
      ss << "restrictions:" << *$1 << ",";
      ss << "terminal_or:\"" << *$2 << "\",";
      ss << "restrictions_and:" << *$3;
      ss << "}";

      $$ = new string(ss.str());
    }
  | restrictions_and
    {
      stringstream ss;

      ss << "{";
      ss << "restrictions_and:" << *$1;
      ss << "}";

      $$ = new string(ss.str());
    }
  ;

restrictions_and:
  restrictions_and terminal_and restrictions_not
    {
      stringstream ss;

      ss << "{";
      ss << "restrictions_and:" << *$1 << ",";
      ss << "terminal_and:\"" << *$2 << "\",";
      ss << "restrictions_not:" << *$3;
      ss << "}";

      $$ = new string(ss.str());
    }
  |	restrictions_and restrictions_not	/* same as AND */
    {
      stringstream ss;

      ss << "{";
      ss << "restrictions_and:" << *$1 << ",";
      ss << "restrictions_not:" << *$2;
      ss << "}";

      $$ = new string(ss.str());
    }
  | restrictions_not
    {
      stringstream ss;

      ss << "{";
      ss << "restrictions_not:" << *$1;
      ss << "}";

      $$ = new string(ss.str());
    }
  ;

restrictions_not:
  terminal_not restrictions_not
    {
      stringstream ss;

      ss << "{";
      ss << "terminal_not:\"" << *$1 << "\",";
      ss << "restrictions_not:" << *$2;
      ss << "}";

      $$ = new string(ss.str());
    }
  |	lpar restrictions rpar
    {
      stringstream ss;

      ss << "{";
      ss << "lpar:\"" << *$1 << "\",";
      ss << "restrictions:" << *$2 << ",";
      ss << "rpar:\"" << *$3 << "\"";
      ss << "}";

      $$ = new string(ss.str());
    }
  | restriction /* break precedence, [] on tgrep*/
    {
      stringstream ss;

      ss << "{";
      ss << "restriction:" << *$1;
      ss << "}";

      $$ = new string(ss.str());
    }
  ;

restriction:
  op search_second
    {
      stringstream ss;

      ss << "{";
      ss << "op:\"" << *$1 << "\",";
      ss << "search_second:" << *$2;
      ss << "}";

      $$ = new string(ss.str());
    }
  ;

search_second:
  lpar search_expression rpar
    {
      stringstream ss;

      ss << "{";
      ss << "lpar:\"" << *$1 << "\",";
      ss << "search_expression:" << *$2 << ",";
      ss << "rpar:\"" << *$3 << "\"";
      ss << "}";

      $$ = new string(ss.str());
    }
  | search_primary
    {
      stringstream ss;

      ss << "{";
      ss << "search_primary:" << *$1;
      ss << "}";

      $$ = new string(ss.str());
    }
  ;


search_primary:
  node_specifier
    { // TODO: See if this rule can be removed, because its useless
      auto result = *$1;
      stringstream ss;
      ss << "{";
      ss << "node_specifier:" << nodenameResultToString(result);
      ss << "}";
      $$ = new string(ss.str());
    }
  ;

node_specifier:
  nodename
    {
      try 
      {
        istringstream input(*$1);
        NodenameMachine machine(input);
        auto result = machine.run();
        $$ = new Nodename::NodenameResult(result);
      }
      catch (const std::exception& e)
      {
        // std::cout << e.what() << std::endl;
        yyerror(e.what());
      }
      catch (const char* error)
      {
        // std::cout << error << std::endl;
        yyerror(error);
      }

      // stringstream ss;
      // ss << "{";
      // ss << "nodename:\"" << result.regex << "\"";
      // // ss << "nodename:\"" << *$1 << "\"";
      // ss << "}";

      // // delete $1;
      // $$ = new string(ss.str());

      // stringstream ss;
      // Machine machine = Machine(string(yytext));
      // Nodespec node_spec = machine.execute();

      // if (node_spec.type == NODE_EXCEPTION)
      //   yyerror(node_spec.errors.c_str());

      // ss << "<node_name="<< node_spec.regex.c_str() << ">";

      /* for more comprehensive debug */

      /*

      string type_of_nodespec_array[] = {"NODE_EXCEPTION","SIMPLE_NODE","RANGE_PLACEHOLDER","EMPTY_NODE"};
      string type_array[] = {"COPY_PLACEHOLDER_FULL","CUT_PLACEHOLDER_FULL","COPY_PLACEHOLDER_REF","CUT_PLACEHOLDER_REF","NONE"};

      ss << endl << "=======" << endl;
      ss << " node_name "<< string(yytext) << endl;
      ss << "  regex: " << node_spec.regex.c_str() << endl;
      ss << "  type_of_nodespec " << type_of_nodespec_array[node_spec.type_of_nodespec+1] << endl;
      ss << "  type " << type_array[node_spec.type] << endl;
      ss << "  holder_number " << node_spec.holder_number << endl;
      ss << "  parenthesis " << node_spec.parenthesis << endl;
      ss << "  holder_start " << node_spec.holder_start << endl;
      ss << "  errors " << node_spec.errors;
      ss << endl << "=======" << endl;

      */

      // $$ = new string(ss.str()); 
    }
  | end_marker
    {
      $$ = new Nodename::NodenameResult();

      // stringstream ss;

      // ss << "{";
      // ss << "end_marker:\"" << *$1 << "\"";
      // ss << "}";

      // $$ = new string(ss.str());
    }
  ;

// replacement_expression: tree_seq;
// tree_seq: tree_seq tree  |  tree   ;
// tree: node |  // folha
//       lpar node tree_seq rpar ;      
// node: node |                        /* similar to nodename */
//       primary_placeholder_instance |
//       auxiliary_placeholder_instance |
// 	  ;

%%

std::string nodenameResultToString(Nodename::NodenameResult result)
{
  std::stringstream stream;

  std::string types[] = {
    "SIMPLE_NODE",
    "NODE_PLACEHOLDER",
    "SUBTREE_RANGE_PLACEHOLDER",
    "END_MARKER"
  };

  std::string placeholders[] = {
    "NONE",
    "CUT",
    "COPY"
  };

  std::string defOrRefs[] = {
    "NONE",
    "DEFINITION",
    "REFERENCE"
  };

  stream << "{";
  stream << "type:\"" << types[(int)result.type] << "\",";
  stream << "placeholder:\"" << placeholders[(int)result.placeholder] << "\",";
  stream << "placeholderNumber:" << result.placeholderNumber << ",";
  stream << "undetermined:" << (result.undetermined ? "true" : "false") << ",";
  stream << "freeOfContext:" << (result.freeOfContext ? "true" : "false") << ",";
  stream << "defOrRef:\"" << defOrRefs[(int)result.defOrRef] << "\",";
  stream << "regex:\"" << result.regex << "\"";
  stream << "}";

  return stream.str();
}

int main(int argc, char *argv[]) 
{
  if (argc > 1)
  {
    yyin = fopen(argv[1], "r");

    if (!yyin) {
      perror("fopen");
      return 1;
    }
  }
  else
    yyin = stdin;

  yyparse();

  if (yyin != stdin)
    fclose(yyin);

  return 0;
}

int yyerror(const char *s)
{
  fprintf(stderr, "ERROR: %s, in line %d, column %d, near token %s\n", s, yylineno, yycolumn, yytext);
  exit(-1);
}