%{
  #include <iostream> // std::cout, std::endl
  #include <sstream> // std::stringstream, std::istringstream

  #include "ast-node.hpp"
  #include "nodename_machine.hpp"
  #include "replacement-node.hpp"
  #include "syntax-tree.hpp"
  #include "transducer.hpp"
  #include "transducer-builder.hpp"

  using namespace std;
  using namespace Nodename;
  using namespace Ast;
  using namespace Transduction;

  // TODO: verify if all these declarion are being used
  extern FILE *yyin;   // Declaration of the yyin variable generated by lex that points to the input file
  extern char *yytext; // Declaration of the yytext variable generated by lex
  extern int yylineno; // Declaration of yylineno variable generated by lex
  extern int yycolumn; // Declaration of yycolumn variable defined in yacc file

  extern void yy_scan_string(const char *str); // Declaration of the yy_scan_string function generated by lex
  extern int yylex(void); // Declaration of the yylex function generated by lex
  int yyerror(const char *s); // Declaration of the yyerror function defined below
  int yywarn(const char *s); // Declaration of the yyerror function defined below

  NodenameInfoSet searchExpressionDefinitions; // Global variable used in replacement expression

  // TODO: Remove it later
  std::string NodenameInfoToString(NodenameInfo); // Auxiliary function defined below

  // TODO: Remove it later
  std::ostream& operator<<(std::ostream& os, AstNode& node)
  {
    os << "{";

    if (node.isLeaf())
      os << "\"root\":\"" << node.data.leaf.nodenameInfo->regex << "\",";
    else
      os << "\"root\":\"" << node.data.internal.operation << "\",";
    
    if (node.left)
      os << "\"left\":" << *node.left << ",";
    else
      os << "\"left\":null,";

    if (node.right)
      os << "\"right\":" << *node.right;
    else
      os << "\"right\":null";

    os << "}";
    return os;
  }
%}

%code requires {
  #include <string>
  #include "ast-node.hpp"
  #include "replacement-node.hpp"
}

/* Definition of union used to define terminal and non-terminal types */
%union {
  std::string *lexem;
  Ast::AstNode *astNode;
  Ast::ReplacementNode *replacementNode;
  std::vector<Ast::ReplacementNode*> *treeSeq;
};

%token <lexem> op end_marker lpar nodename rpar subtree_range terminal_and terminal_not terminal_or turnsto

%type <astNode> start
%type <astNode> search_expression
%type <astNode> opt_restrictions
%type <astNode> restrictions
%type <astNode> restrictions_and
%type <astNode> restrictions_not
%type <astNode> restriction
%type <astNode> search_second
%type <astNode> search_primary
%type <astNode> node_specifier

%type <treeSeq> replacement_expression
%type <treeSeq> tree_seq
%type <replacementNode> tree
%type <replacementNode> node

%%

start:
  search_expression turnsto { if ($1->isInternal()) searchExpressionDefinitions = $1->data.internal.definitions; } replacement_expression
  {
    if ($1->isLeaf())
    {
      // Check if the main placehoilder exists
      NodenameInfo *nodenameInfo = $1->data.leaf.nodenameInfo;
      if (nodenameInfo->placeholder != Placeholder::CUT 
        || nodenameInfo->placeholderNumber != 0 
        || nodenameInfo->defOrRef != DefOrRef::DEFINITION)
      {
        yyerror("The search expression needs to have a definition to main placeholder."); // TODO: improve this message
      } 
    }
    else
    {
      // Check if all references are defined
      NodenameInfoSet& references = $1->data.internal.references;
      if (!references.empty())
        yyerror("There are references that are not defined in search expression."); // TODO: improve this message
      
      // Check if the main placehoilder exists
      NodenameInfoSet& definitions = $1->data.internal.definitions;
      NodenameInfo nodenameWithPlaceholderNumber0;
      nodenameWithPlaceholderNumber0.placeholderNumber = 0;
      NodenameInfoSet::iterator it = definitions.find(&nodenameWithPlaceholderNumber0);
      if (it == definitions.end() || (*it)->placeholder != Placeholder::CUT || (*it)->defOrRef != DefOrRef::DEFINITION)
        yyerror("The search expression needs to have a definition to main placeholder."); // TODO: improve this message
    }

    // TODO: Verify if something yet needs to be checked
    auto tree = new SyntaxTree("NP", nullptr);
    tree->addChild(new SyntaxTree("PP", nullptr));
    Transducer* transducer = TransducerBuilder()
      .setIteratorStrategyType(SyntaxTreeIteratorStrategyType::PRE_ORDER)
      .setTransversalStrategyType(TransversalStrategyType::STOP)
      .build();
    
    transducer->applyTransductionRule(tree, $1, $4);
    
    delete transducer;
    // cout << *$1;
    $$ = $1;
  }
  ;

search_expression:
  search_primary opt_restrictions
  {
    NodenameInfo *searchPrimaryNodename = $1->data.leaf.nodenameInfo;

    if ($2 != nullptr)
    {
      NodenameInfoSet& restrictionsDefinitions = $2->data.internal.definitions;
      NodenameInfoSet& restrictionsReferences = $2->data.internal.references;

      string operation = ":>"; // TODO: create a constant for this symbol
      NodenameInfoSet definitions = restrictionsDefinitions;
      NodenameInfoSet references = restrictionsReferences;

      if (searchPrimaryNodename->defOrRef == DefOrRef::DEFINITION)
      {
        NodenameInfoSet::iterator restrDefIt = restrictionsDefinitions.find(searchPrimaryNodename);
        if (restrDefIt != restrictionsDefinitions.end())
          yyerror("The nodename is already defined before."); // TODO: Correct/Improve this error message
        
        NodenameInfoSet::iterator restrRefIt = restrictionsReferences.find(searchPrimaryNodename);
        if (restrRefIt != restrictionsReferences.end())
        {
          if (searchPrimaryNodename->placeholder != (*restrRefIt)->placeholder)
            yyerror("The nodename reference must have the same placeholder type as its definition."); // TODO: Correct/Improve this error message
          references.erase(searchPrimaryNodename); // Resolve the search primary reference
        }

        definitions.insert(searchPrimaryNodename);
      }
      else if (searchPrimaryNodename->defOrRef == DefOrRef::REFERENCE)
      {
        NodenameInfoSet::iterator restrDefIt = restrictionsDefinitions.find(searchPrimaryNodename);
        if (restrDefIt != restrictionsDefinitions.end())
          yyerror("The nodename is defined after its reference."); // TODO: Correct/Improve this error message

        NodenameInfoSet::iterator restrRefIt = restrictionsReferences.find(searchPrimaryNodename);
        if (restrRefIt != restrictionsReferences.end())
        {
          if (searchPrimaryNodename->placeholder != (*restrRefIt)->placeholder)
            yyerror("The nodename reference must have the same placeholder type in all references."); // TODO: Correct/Improve this error message
        }
        else
          references.insert(searchPrimaryNodename);
      }

      $$ = new AstNode(nullptr, $1, $2, operation, definitions, references); // TODO: Change to *definitions and instantiate this dinamically
    }
    else
      $$ = $1;
  }
  ;

opt_restrictions:
  restrictions
  {
    $$ = $1;
  }
  |
  {
    $$ = nullptr;
  }
  ;

restrictions:
  restrictions terminal_or restrictions_and
  {
    NodenameInfoSet& leftDefinitions = $1->data.internal.definitions;
    NodenameInfoSet& leftReferences = $1->data.internal.references;
    NodenameInfoSet& rightDefinitions = $3->data.internal.definitions;
    NodenameInfoSet& rightReferences = $3->data.internal.references;

    string operation = *$2;
    NodenameInfoSet definitions;
    NodenameInfoSet references;

    // Rules for nodenames visibility of the OR operator:
    // def x def: must have the same type to propagate; otherwise, it results in an error.
    // def x ref: results in an error because it is referenced but not defined on this side.
    // def x ---: does not propagate and may generate a warning.
    // ref x def: results in an error because it is referenced but not defined on this side.
    // ref x ref: must have the same type to propagate; otherwise, it results in an error.
    // ref x ---: results in an error because the reference is not present on the other side and is unresolved on this side.
    // --- x def: does not propagate and may generate a warning.
    // --- x ref: results in an error because the reference is not present on the other side and is unresolved on this side.
    
    // The code bellow was implemented in the most straightforward way possible for readability purposes,
    // but it can be optimized in the future.

    for (NodenameInfo *leftDef : leftDefinitions)
    {
      NodenameInfoSet::iterator rightDefIt = rightDefinitions.find(leftDef);
      NodenameInfoSet::iterator rightRefIt = rightReferences.find(leftDef);

      if (rightDefIt != rightDefinitions.end()) // def x def
      {
        if (leftDef->placeholder != (*rightDefIt)->placeholder)
          yyerror("The nodename definition must have the same placeholder type in every sides of the OR operator."); // TODO: Correct/Improve this error message
        else
          definitions.insert(leftDef);
      } 
      else if (rightRefIt != rightReferences.end()) // def x ref
        yyerror("The node name reference is not being defined on the side of the OR operator where it is used."); // TODO: Correct/Improve this error message
      else // def x ---
        yywarn("The nodename definition is not present on every side of the OR operator, so it will not be accessible outside the side where it is defined."); // TODO: Correct/Improve this warn message
    }

    for (NodenameInfo *leftRef : leftReferences)
    {
      NodenameInfoSet::iterator rightDefIt = rightDefinitions.find(leftRef);
      NodenameInfoSet::iterator rightRefIt = rightReferences.find(leftRef);

      if (rightDefIt != rightDefinitions.end()) // ref x def
      {
        yyerror("The node name reference is not being defined on the side of the OR operator where it is used."); // TODO: Correct/Improve this error message
      }
      else if (rightRefIt != rightReferences.end()) // ref x ref
      {
        if (leftRef->placeholder != (*rightRefIt)->placeholder)
          yyerror("The nodename reference must have the same placeholder type in every sides of the OR operator."); // TODO: Correct/Improve this error message
        else
          references.insert(leftRef);
      }
      else // ref x ---
        yyerror("The nodename reference is not present on every side of the OR operator, resulting in an unresolved reference."); // TODO: Correct/Improve this error message
    }

    for (NodenameInfo *rightDef : rightDefinitions)
    {
      NodenameInfoSet::iterator leftDefIt = leftDefinitions.find(rightDef);
      NodenameInfoSet::iterator leftRefIt = leftReferences.find(rightDef);

      if (leftDefIt == leftDefinitions.end() && leftRefIt == leftReferences.end()) // --- x def
        yywarn("The nodename definition is not present on every side of the OR operator, so it will not be accessible outside the side where it is defined."); // TODO: Correct/Improve this warn message
    }

    for (NodenameInfo *rightRef : rightReferences)
    {
      NodenameInfoSet::iterator leftDefIt = leftDefinitions.find(rightRef);
      NodenameInfoSet::iterator leftRefIt = leftReferences.find(rightRef);

      if (leftDefIt == leftDefinitions.end() && leftRefIt == leftReferences.end()) // --- x ref
        yyerror("The nodename reference is not present on every side of the OR operator, resulting in an unresolved reference."); // TODO: Correct/Improve this error message
    }

    $$ = new AstNode(nullptr, $1, $3, operation, definitions, references); // TODO: Change to *definitions and instantiate this dinamically
    delete $2;
  }
  | restrictions_and
  {
    $$ = $1;
  }
  ;

restrictions_and:
  restrictions_and terminal_and restrictions_not
  {
    NodenameInfoSet& leftDefinitions = $1->data.internal.definitions;
    NodenameInfoSet& leftReferences = $1->data.internal.references;
    NodenameInfoSet& rightDefinitions = $3->data.internal.definitions;
    NodenameInfoSet& rightReferences = $3->data.internal.references;

    string operation = *$2;
    NodenameInfoSet definitions = leftDefinitions;
    NodenameInfoSet references = leftReferences;

    for (NodenameInfo *rightDef : rightDefinitions)
    {
      bool definedBefore = leftDefinitions.find(rightDef) != leftDefinitions.end();
      bool referencedBefore = leftReferences.find(rightDef) == leftReferences.end();

      if (definedBefore)
        yyerror("The nodename definition is already defined before."); // TODO: Correct/Improve this error message
      else if (referencedBefore)
        yyerror("The nodename definition is being referenced before."); // TODO: Correct/Improve this error message
      else
        definitions.insert(rightDef);
    }

    for (NodenameInfo *rightRef : rightReferences)
    {
      NodenameInfoSet::iterator leftDefIt = leftDefinitions.find(rightRef);
      NodenameInfoSet::iterator leftRefIt = leftReferences.find(rightRef);
      
      bool isDefinedBefore = leftDefIt != leftDefinitions.end();
      bool isDefinedBeforeWithDifferentPlaceholder = isDefinedBefore
        && (*leftDefIt)->placeholder != rightRef->placeholder;
      bool isReferencedBeforeWithDifferentPlaceholder = leftRefIt != leftReferences.end()
        && (*leftRefIt)->placeholder != rightRef->placeholder;

      if (isDefinedBeforeWithDifferentPlaceholder)
        yyerror("The nodename reference is defined before, but with a different placeholder type."); // TODO: Correct/Improve this error message
      else if (isReferencedBeforeWithDifferentPlaceholder)
        yyerror("The nodename reference is referenced before, but with a different placeholder type."); // TODO: Correct/Improve this error message
      else if (!isDefinedBefore)
        references.insert(rightRef);
    }

    $$ = new AstNode(nullptr, $1, $3, operation, definitions, references); // TODO: Change to *definitions and instantiate this dinamically
    delete $2;
  }
  |	restrictions_and restrictions_not	/* same as AND */
  {
    NodenameInfoSet& leftDefinitions = $1->data.internal.definitions;
    NodenameInfoSet& leftReferences = $1->data.internal.references;
    NodenameInfoSet& rightDefinitions = $2->data.internal.definitions;
    NodenameInfoSet& rightReferences = $2->data.internal.references;

    string operation = "&"; // TODO: create a constant for this symbol
    NodenameInfoSet definitions = leftDefinitions;
    NodenameInfoSet references = leftReferences;

    for (NodenameInfo *rightDef : rightDefinitions)
    {
      bool definedBefore = leftDefinitions.find(rightDef) != leftDefinitions.end();
      bool referencedBefore = leftReferences.find(rightDef) == leftReferences.end();

      if (definedBefore)
        yyerror("The nodename definition is already defined before."); // TODO: Correct/Improve this error message
      else if (referencedBefore)
        yyerror("The nodename definition is being referenced before."); // TODO: Correct/Improve this error message
      else
        definitions.insert(rightDef);
    }

    for (NodenameInfo *rightRef : rightReferences)
    {
      NodenameInfoSet::iterator leftDefIt = leftDefinitions.find(rightRef);
      NodenameInfoSet::iterator leftRefIt = leftReferences.find(rightRef);
      
      bool isDefinedBefore = leftDefIt != leftDefinitions.end();
      bool isDefinedBeforeWithDifferentPlaceholder = isDefinedBefore
        && (*leftDefIt)->placeholder != rightRef->placeholder;
      bool isReferencedBeforeWithDifferentPlaceholder = leftRefIt != leftReferences.end()
        && (*leftRefIt)->placeholder != rightRef->placeholder;

      if (isDefinedBeforeWithDifferentPlaceholder)
        yyerror("The nodename reference is defined before, but with a different placeholder type."); // TODO: Correct/Improve this error message
      else if (isReferencedBeforeWithDifferentPlaceholder)
        yyerror("The nodename reference is referenced before, but with a different placeholder type."); // TODO: Correct/Improve this error message
      else if (!isDefinedBefore)
        references.insert(rightRef);
    }

    $$ = new AstNode(nullptr, $1, $2, operation, definitions, references); // TODO: Change to *definitions and instantiate this dinamically
  }
  | restrictions_not
  {
    $$ = $1;
  }
  ;

restrictions_not:
  terminal_not restrictions_not
  {
    string operation = *$1;
    NodenameInfoSet definitions;
    NodenameInfoSet references;

    $$ = new AstNode(nullptr, $2, nullptr, operation, definitions, references); // TODO: Change to *definitions and instantiate this dinamically
    delete $1;
  }
  |	lpar restrictions rpar
  {
    $$ = $2;
  }
  | restriction /* break precedence, [] on tgrep*/
  {
    $$ = $1;
  }
  ;

restriction:
  op search_second
  {
    string *operation = $1;
    NodenameInfoSet *definitions = new NodenameInfoSet;
    NodenameInfoSet *references = new NodenameInfoSet;

    if ($2->isLeaf())
    {
      NodenameInfo *nodenameInfo = $2->data.leaf.nodenameInfo;

      if (nodenameInfo->defOrRef == DefOrRef::DEFINITION)
        definitions->insert(nodenameInfo);
      else if (nodenameInfo->defOrRef == DefOrRef::REFERENCE)
        references->insert(nodenameInfo);
    }
    else
    {
      *definitions = $2->data.internal.definitions;
      *references = $2->data.internal.references;
    }

    $$ = new AstNode(nullptr, $2, nullptr, *operation, *definitions, *references); // TODO: Change to *definitions and instantiate this dinamically
    delete operation;
    delete definitions;
    delete references;
  }
  ;

search_second:
  lpar search_expression rpar
  {
    $$ = $2;
  }
  | search_primary
  {
    $$ = $1;
  }
  ;

search_primary:
  node_specifier
  {
    // TODO: See if this rule can be removed, because it's useless
    $$ = $1;
  }
  ;

node_specifier:
  nodename
  {
    try
    {
      istringstream input(*$1);
      NodenameInfo nodenameInfo = NodenameMachine(input).run(); // TODO: Change this method to return a pointer to NodenameInfo
      $$ = new AstNode(nullptr, nullptr, nullptr, new NodenameInfo(nodenameInfo));
      delete $1;
    }
    catch (const exception& e)
    {
      yyerror(e.what());
    }
    catch (const char* error)
    {
      yyerror(error);
    }
  }
  | end_marker
  {
    $$ = new AstNode(nullptr, nullptr, nullptr, NodenameInfo::newEndMarkerInstance());
    delete $1;
  }
  | subtree_range
  {
    string lexem = *$1;
    Placeholder placeholder = (lexem[0] == '[') ? Placeholder::CUT : Placeholder::COPY;
    int placeholderNumber = 0;

    size_t colonPos = lexem.find(':', 1);
    if (colonPos != string::npos)
      placeholderNumber = stoi(lexem.substr(1, colonPos - 1));

    $$ = new AstNode(nullptr, nullptr, nullptr, NodenameInfo::newSubtreeRangeInstance(placeholder, placeholderNumber));
    delete $1;
  }
  ;

replacement_expression: 
  tree_seq
  {
    $$ = $1;
  }
  | /* empty */
  {
    $$ = new vector<ReplacementNode*>;
  }
  ;

tree_seq: 
  tree_seq tree
  {
    vector<ReplacementNode*> &treeSeq = *$1;
    ReplacementNode* tree = $2;
    treeSeq.push_back(tree);
    $$ = &treeSeq;
  }
  | tree
  {
    $$ = new vector<ReplacementNode*>{ $1 };
  }
  ;

tree:
  node
  {
    $$ = $1;
  }
  | lpar node tree_seq rpar
  {
    NodenameInfo *node = $2->nodenameInfo;
    vector<ReplacementNode*> *treeSeq = $3;

    if (node->placeholder != Placeholder::NONE)
      yyerror("The tree root in replacement expression cannot have a placeholder."); // TODO: Correct/Improve this error message

    $$ = new ReplacementNode(node, treeSeq);
  }
  ;

node:
  nodename
  {
    try
    {
      istringstream input(*$1);
      NodenameInfo nodenameInfo = NodenameMachine(input).run(); // TODO: Change this method to return a pointer to NodenameInfo

      if (!nodenameInfo.freeOfContext)
        yyerror("Nodenames in replacement expression cannot have left or right contexts."); // TODO: Correct/Improve this error message
      if (nodenameInfo.undetermined)
        yyerror("Nodenames in replacement expression cannot contain ANY, WILDCARD or REGEX."); // TODO: Correct/Improve this error message
      
      if (nodenameInfo.placeholder != Placeholder::NONE)
      {
        NodenameInfoSet::iterator it = searchExpressionDefinitions.find(&nodenameInfo);
        if (it == searchExpressionDefinitions.end())
          yyerror("The placeholder is not defined in the search expression.");  // TODO: Correct/Improve this error message
        if ((*it)->placeholder != nodenameInfo.placeholder)
          yyerror("The placeholder has a different type of its definition in the search expression.");  // TODO: Correct/Improve this error message
      }

      $$ = new ReplacementNode(new NodenameInfo(nodenameInfo));
      delete $1;
    }
    catch (const exception& e)
    {
      yyerror(e.what());
    }
    catch (const char* error)
    {
      yyerror(error);
    }
  }
  ;

%%

std::string NodenameInfoToString(NodenameInfo result)
{
  std::stringstream stream;

  std::string types[] = {
    "SIMPLE_NODE",
    "NODE_PLACEHOLDER",
    "SUBTREE_RANGE_PLACEHOLDER",
    "END_MARKER"
  };

  std::string placeholders[] = {
    "NONE",
    "CUT",
    "COPY"
  };

  std::string defOrRefs[] = {
    "NONE",
    "DEFINITION",
    "REFERENCE"
  };

  stream << "{";
  stream << "type:\"" << types[(int)result.type] << "\",";
  stream << "placeholder:\"" << placeholders[(int)result.placeholder] << "\",";
  stream << "placeholderNumber:" << result.placeholderNumber << ",";
  stream << "undetermined:" << (result.undetermined ? "true" : "false") << ",";
  stream << "freeOfContext:" << (result.freeOfContext ? "true" : "false") << ",";
  stream << "defOrRef:\"" << defOrRefs[(int)result.defOrRef] << "\",";
  stream << "regex:\"" << result.regex << "\"";
  stream << "}";

  return stream.str();
}

void printUsage()
{
  cout << "Usage: tsed [TRANSDUCTION] [FILE]..." << endl;
}

void printHelp()
{
  printUsage();
  cout << "Applies a transduction rule to the treebanks present in each [FILE]." << endl;
  cout << "The trees in each [FILE] must be written in the Penn Treebank format." << endl;
  cout << "Example: tsed '[NP] ==> NNP' input.txt" << endl;
  cout << endl;
  cout << "Exit status 0 if any tree is modified, 1 if no tree is modified, and -1 in case of an error." << endl;
  // TODO: Improve this manual
}

int main(int argc, char *argv[]) 
{
  for (int i = 0; i < argc; i++)
  {
    string argument(argv[i]);
    if (argument.compare("--help") == 0)
    {
      printHelp();
      return 1;
    }
  }

  if (argc < 3)
  {
    printUsage();
    cout << "Try 'tsed --help' for more information." << endl;
    return -1;
  }

  // if (argc > 1)
  // {
  //   yyin = fopen(argv[1], "r");

  //   if (!yyin) {
  //     perror("fopen");
  //     return 1;
  //   }
  // }
  // else
  //   yyin = stdin;
  cout << argv[1] << endl;
  yy_scan_string(argv[1]);
  yyparse();

  // if (yyin != stdin)
  //   fclose(yyin);

  cout << "\n\nExiting Success...\n"; // TODO: Remove it later
  return 0;
}

int yyerror(const char *s)
{
  fprintf(stderr, "ERROR: %s in line %d, column %d, near token %s\n", s, yylineno, yycolumn, yytext);
  exit(-1);
}

int yywarn(const char *s)
{
  fprintf(stderr, "WARNING: %s in line %d, column %d, near token %s\n", s, yylineno, yycolumn, yytext);
  return 0;
}