%{
  #include <iostream> // std::cout, std::endl
  #include <sstream> // std::stringstream, std::istringstream

  #include "nodename-machine.hpp"
  #include "parsing-rules.hpp"
  #include "search-expression.hpp"
  #include "syntax-tree.hpp"
  #include "transducer.hpp"
  #include "transducer-builder.hpp"
  #include "transduction-rule.hpp"

  using namespace std;
  using namespace Nodename;
  using namespace Transduction;

  // TODO: verify if all these declarion are being used
  extern FILE *yyin;   // Declaration of the yyin variable generated by lex that points to the input file
  extern char *yytext; // Declaration of the yytext variable generated by lex
  extern int yylineno; // Declaration of yylineno variable generated by lex
  extern int yycolumn; // Declaration of yycolumn variable defined in yacc file

  extern void yy_scan_string(const char *str); // Declaration of the yy_scan_string function generated by lex
  extern int yylex(void); // Declaration of the yylex function generated by lex
  int yyerror(const char *s); // Declaration of the yyerror function defined below
  int yywarn(const char *s); // Declaration of the yyerror function defined below

  Transduction::TransductionRule *yaccResult;

  NodenameInfoSet searchExpressionDefinitions; // Global variable used in replacement expression
%}

%code requires {
  #include <string>
  #include "nodename-expression.hpp"
  #include "replacement-leaf-node.hpp"
  #include "replacement-tree.hpp"
  #include "search-expression.hpp"
  #include "transduction-rule.hpp"
}

/* Definition of union used to define terminal and non-terminal types */
%union {
  std::string *lexem;
  Transduction::Search::SearchExpression *searchExpression;
  Transduction::Search::NodenameExpression *nodenameExpression;
  Transduction::Replacement::ReplacementLeafNode *replacementNode;
  Transduction::Replacement::ReplacementTree *replacementTree;
  Transduction::Replacement::TreeSequence *treeSequence;
  Transduction::TransductionRule *transductionRule;
};

%token <lexem> op end_marker lpar nodename rpar subtree_range terminal_and terminal_not terminal_or turnsto

%type <transductionRule> transduction
%type <searchExpression> search_expression
%type <searchExpression> opt_restrictions
%type <searchExpression> restrictions
%type <searchExpression> restrictions_and
%type <searchExpression> restrictions_not
%type <searchExpression> restriction
%type <searchExpression> search_second
%type <nodenameExpression> search_primary

%type <treeSequence> replacement_expression
%type <treeSequence> tree_seq
%type <replacementTree> tree
%type <replacementNode> node

%%

transduction:
  search_expression turnsto { searchExpressionDefinitions = $1->getDefinitions(); } replacement_expression
  {
    try
    {
      $$ = yaccResult = Parsing::parseTransduction($1, $4);
      delete $2;
    }
    catch (const exception& e)
    {
      delete $1;
      delete $2;
      delete $4;
      yyerror(e.what());
    }
    catch (const char* error)
    {
      delete $1;
      delete $2;
      delete $4;
      yyerror(error);
    }
  }
  ;

search_expression:
  search_primary opt_restrictions
  {
    try
    {
      $$ = Parsing::parseSearchExpression($1, $2);
    }
    catch (const exception& e)
    {
      delete $1;
      delete $2;
      yyerror(e.what());
    }
    catch (const char* error)
    {
      delete $1;
      delete $2;
      yyerror(error);
    }
  }
  ;

opt_restrictions:
  restrictions
  {
    $$ = $1;
  }
  |
  {
    $$ = nullptr;
  }
  ;

restrictions:
  restrictions terminal_or restrictions_and
  {
    try
    {
      $$ = Parsing::parseOr($1, $3);
      delete $2;
    }
    catch (const exception& e)
    {
      delete $1;
      delete $2;
      delete $3;
      yyerror(e.what());
    }
    catch (const char* error)
    {
      delete $1;
      delete $2;
      delete $3;
      yyerror(error);
    }
  }
  | restrictions_and
  {
    $$ = $1;
  }
  ;

restrictions_and:
  restrictions_and terminal_and restrictions_not
  {
    try
    {
      $$ = Parsing::parseAnd($1, $3);
      delete $2;
    }
    catch (const exception& e)
    {
      delete $1;
      delete $2;
      delete $3;
      yyerror(e.what());
    }
    catch (const char* error)
    {
      delete $1;
      delete $2;
      delete $3;
      yyerror(error);
    }
  }
  |	restrictions_and restrictions_not	/* same as AND */
  {
    
    try
    {
      $$ = Parsing::parseAnd($1, $2);
    }
    catch (const exception& e)
    {
      delete $1;
      delete $2;
      yyerror(e.what());
    }
    catch (const char* error)
    {
      delete $1;
      delete $2;
      yyerror(error);
    }
  }
  | restrictions_not
  {
    $$ = $1;
  }
  ;

restrictions_not:
  terminal_not restrictions_not
  {
    try
    {
      $$ = Parsing::parseNot($2);
      delete $1;
    }
    catch (const exception& e)
    {
      delete $1;
      delete $2;
      yyerror(e.what());
    }
    catch (const char* error)
    {
      delete $1;
      delete $2;
      yyerror(error);
    }
  }
  |	lpar restrictions rpar
  {
    $$ = $2;
  }
  | restriction
  {
    $$ = $1;
  }
  ;

restriction:
  op search_second
  {
    try
    {
      $$ = Parsing::parseRestriction(*$1, $2);
      delete $1;
    }
    catch (const exception& e)
    {
      delete $1;
      delete $2;
      yyerror(e.what());
    }
    catch (const char* error)
    {
      delete $1;
      delete $2;
      yyerror(error);
    }
  }
  ;

search_second:
  lpar search_expression rpar
  {
    $$ = $2;
  }
  | search_primary
  {
    $$ = $1;
  }
  ;

search_primary:
  nodename
  {
    try
    {
      $$ = Parsing::parseNodename(*$1);
      delete $1;
    }
    catch (const exception& e)
    {
      delete $1;
      yyerror(e.what());
    }
    catch (const char* error)
    {
      delete $1;
      yyerror(error);
    }
  }
  | end_marker
  {
    $$ = Parsing::parseEndMarker();
    delete $1;
  }
  | subtree_range
  {
    $$ = Parsing::parseSubtreeRange(*$1);
    delete $1;
  }
  ;

replacement_expression: 
  tree_seq
  {
    $$ = $1;
  }
  | /* empty */
  {
    $$ = new Transduction::Replacement::TreeSequence;
  }
  ;

tree_seq: 
  tree_seq tree
  {
    $$ = Parsing::parseReplacementTreeSequence($1, $2);
  }
  | tree
  {
    $$ = new Transduction::Replacement::TreeSequence({ $1 });
  }
  ;

tree:
  node
  {
    $$ = $1;
  }
  | lpar node tree_seq rpar
  {
    try
    {
      $$ = Parsing::parseReplacementTree($2, $3);
      delete $1;
      delete $4;
    }
    catch (const exception& e)
    {
      delete $1;
      delete $2;
      delete $3;
      delete $4;
      yyerror(e.what());
    }
    catch (const char* error)
    {
      delete $1;
      delete $2;
      delete $3;
      delete $4;
      yyerror(error);
    }
  }
  ;

node:
  nodename
  {
    try
    {
      $$ = Parsing::parseReplacementNode(*$1, searchExpressionDefinitions);
      delete $1;
    }
    catch (const exception& e)
    {
      delete $1;
      yyerror(e.what());
    }
    catch (const char* error)
    {
      delete $1;
      yyerror(error);
    }
  }
  ;

%%

void printUsage()
{
  cout << "Usage: tsed [TRANSDUCTION] [FILE]..." << endl;
}

void printHelp()
{
  printUsage();
  cout << "Applies a transduction rule to the treebanks present in each [FILE]." << endl;
  cout << "The trees in each [FILE] must be written in the Penn Treebank format." << endl;
  cout << "Example: tsed '[NP] ==> NNP' input.txt" << endl;
  cout << endl;
  cout << "Exit status 0 if any tree is modified, 1 if no tree is modified, and -1 in case of an error." << endl;
  // TODO: Improve this manual
}

// TODO: Move this to a main file and adjust Makefile
int main(int argc, char *argv[]) 
{
  for (int i = 0; i < argc; i++)
  {
    string argument(argv[i]);
    if (argument.compare("--help") == 0)
    {
      printHelp();
      return 1;
    }
  }

  if (argc < 3)
  {
    printUsage();
    cout << "Try 'tsed --help' for more information." << endl;
    return -1;
  }

  // cout << "Transduction rule to be processed: " << argv[1] << endl;
  yy_scan_string(argv[1]);

  // TODO: use %parser-param to pass params here
  // https://www.gnu.org/software/bison/manual/bison.html#index-_0025parse_002dparam:~:text=parse%2Dparam%3A-,Directive%3A%20%25parse%2Dparam%20%7Bargument%2Ddeclaration%7D,-%E2%80%A6%20%C2%B6
  if (yyparse() == 0)
  {
    Transducer* transducer = TransducerBuilder()
      .setIteratorStrategyType(SyntaxTreeIteratorStrategyType::PRE_ORDER)
      .setTransversalStrategyType(TransversalStrategyType::STOP)
      .build();

    for (int i = 2; i < argc; i++)
    {
      string filename(argv[i]);
      // cout << "Processing file: " << filename << endl;
      auto trees = SyntaxTree::readFromFile(filename);

      for (auto *tree : trees)
        transducer->apply(yaccResult, tree);
    }

    delete transducer;
  }

  return 0;
}

int yyerror(const char *s)
{
  fprintf(stderr, "ERROR: %s in line %d, column %d, near token %s\n", s, yylineno, yycolumn, yytext);
  exit(-1);
}

int yywarn(const char *s)
{
  fprintf(stderr, "WARNING: %s in line %d, column %d, near token %s\n", s, yylineno, yycolumn, yytext);
  return 0;
}